language: python
python:
  - "3.6"
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
# command to install dependencies
install:
  - pip install pipenv
  - pipenv install --dev --three
# # command to run tests
script:
  - pipenv run python -m pytest
